BG_SUBTRACTION:
  MOG_MODEL:
    HISTORY: 1000
    THRESHOLD: 16
    DETECT_SHADOWS: True
  ERODE_DILATE:
    KERNEL_SIZE:
      - 2
      - 2
    ITERATIONS: 1
  MORPH_CLOSE:
    KERNEL_SIZE:
      - 7
      - 7
    ITERATIONS: 2
  REDUCE_FRAME_SHAPE_MULTIPLIER: 8

ENTRANCE_DETECTOR:
  YOLO:
    YOLO_MODEL: "n"
    YOLO_CONFIDENCE: 0.25
  ROI:
    ROI_SCALE_MULTIPLIER: 1.75
    MOVING_ROI_PART: 0.2
  PROCESSING:
    SAVE_FRAME_TIMER: 50
    ACTIONS_THRESHOLD: 30
  CENTROID_ANGLE_THRESH:
      FROM: 25
      TO: 90